kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: localstack
subjects:
  - kind: ServiceAccount
    name: localstack
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
